version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "gopkg.in/yaml.v3"
      - dependency-name: "gopkg.in/yaml.v2"
