---
version: 2.1

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-prerelease: &on-tag-prerelease
  branches:
    ignore: /.*/
  tags:
    only: /^([0-9]+(\.[0-9]+)+)-rc.[0-9]+$/

on-tag-release: &on-tag-release
  branches:
    ignore: /.*/
  tags:
    only: /^((([0-9]+)\.([0-9]+)\.([0-9]+))?)$/

jobs:

  static-analysis:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: static code analysis
          command: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck ./...
      - run:
          name: lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
            golangci-lint ./...

workflows:
  version: 2

  development-build:
    jobs:
      - static-analysis
